app:
 version: V1.00.00.0

spring:
 application:
   name: gateway-service
 config:
   import: optional:configserver:${CONFIG_URI:http://localhost:8888/}
 cloud:
   gateway:
     discovery:
       locator:
         enabled: false
         lowerCaseServiceId: true
     routes:
       - id: merchant-service
         uri: lb://merchant-service
         predicates:
           - Path=/api/v1/merchant/**
         filters:
           - StripPrefix=3

       - id: notification-service
         uri: lb://notification-service
         predicates:
           - Path=/api/v1/notification/**
         filters:
           - StripPrefix=3

       - id: ipg-engine
         uri: lb://ipg-engine
         predicates:
             - Path=/ipg/**

       - id: aggregator-service
         uri: lb://aggregator-service
         predicates:
           - Path=/api/v1/aggregator/**
         filters:
           - StripPrefix=3

springdoc:
 enable-native-support: true
 api-docs:
   enabled: true
 swagger-ui:
   enabled: true
   path: /swagger
   config-url: /v3/api-docs/swagger-config
   urls:
     - url: /v3/api-docs
       name: API Gateway Service
       display-name: API Gateway Service

     - url: /api/v1/aggregator/v3/api-docs
       name: Aggregator Service
       display-name: Aggregator Service

     - url: /api/v1/merchant/v3/api-docs
       name: Merchant Service
       display-name: Merchant Service

     - url: /api/v1/notification/v3/api-docs
       name: Notification Service
       display-name: Notification Service

     - url: /ipg/v3/api-docs
       name: Ipg Engine
       display-name: Ipg Engine